### ISSUE TITLE
SVG backend: l:href not working

### ISSUE THREAD

**Issue by alainfrisch** [dbuenzli/qrc#1]
I'm trying to directly embed a SVG QR code in an HTML document (more precisely, I inject the code by setting the innerHTML property), and I get a white square.  It seems that the `<use l:href='#o' ...>`  reference is not properly understood.  Simply dropping the `l:` prefix solves the issue.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href claims that xlink:href is deprecated in SVG 2, but Qrc forces the use of version 1 (is it respected by the browser?).

Also, it works fine if I change the `l:` to `xlink:` without even defining this prefix!  Is there something fishy with the parsing/interpretation of namespaces when parsing (non-X)HTML?

I'm using Chrome 87.0.4280.88.

Anyway, I was also wondering: Is there a strong (performance?/size?) benefit in using a reference instead of inlining the `<rect>` element for each "on" pixel?  I'm concerned by possible clash with other elements with `id='o'` in the same document.

**Comment by dbuenzli** [comment]
> Also, it works fine if I change the `l:` to `xlink:` without even defining this prefix! Is there something fishy with the parsing/interpretation of namespaces when parsing (non-X)HTML?

I have no idea it would be nice to test in other browsers. But the whole story seems a bit [more complicated](https://css-tricks.com/on-xlinkhref-being-deprecated-in-svg/) than what that MDN page says. SVG2 seems to never have really happened (still a draft) and at least at the time when that article was written not having the xlink was an issue for Safari. 

So I rather not follow the MDN advice and stick to the 1.1 standard. It's also unclear what the effect would be for vector graphic drawing programs, the current output was at least tested to read fine in Inkscape.

Note that opening the svg file in the same Chrome works here. I also suspect that if you write the SVG to a data url and inject it via an `img` tag that will work. At least that's what is done the [vg image database](https://erratique.ch/software/vg/demos/) and it works well for similarly generated svg (`xlink` bound to `l`).

> Anyway, I was also wondering: Is there a strong (performance?/size?) benefit in using a reference instead of inlining the `<rect>` element for each "on" pixel?

On my computer, in my limited testing, for the large QRs, yes. 

Doing it that way had a big impact on rendering time and e.g. zooming into the qrcode. For a V40 QR code that has half the modules on, I guess it's the difference between rasterizing *one* square path or  ~15000 of them.

> I'm concerned by possible clash with other elements with `id='o'` in the same document.

It's a legitimate concern. An optional argument should be added to let the client specify the id and maybe using `o` as a default was not such a good idea (I choose it to minimize file size).

**Comment by alainfrisch** [comment]
FWIW, I checked how some online services build SVG QR code.  For instance, https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=Example&format=svg  produces

````xml
<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="147" height="147">
	<!-- Created with https://api.qrserver.com (QR Code API, see goQR.me/api for information) -->
	<title>QR Code</title>
	<desc>Example</desc>
	<rect style="fill:rgb(255, 255, 255);fill-opacity:1" x="0" y="0" width="147" height="147" />
	<g id="elements">
		<path style="fill:rgb(0, 0, 0)" d="M 0,0 l 7,0 0,7 -7,0 z M 7,0 l 7,0 0,7 -7,0 z M 14,0 l 7,0 0,7 -7,0 z M 21,0 l 7,0 0,7 -7,0 z M 28,0 l 7,0 0,7 -7,0 z M 35,0 l 7,0 0,7 -7,0 z M 42,0 l 7,0 0,7 -7,0 z M 70,0 l 7,0 0,7 -7,0 z M 77,0 l 7,0 0,7 -7,0 z M 84,0 l 7,0 0,7 -7,0 z M 98,0 l 7,0 0,7 -7,0 z M 105,0 l 7,0 0,7 -7,0 z M 112,0 l 7,0 0,7 -7,0 z M 119,0 l 7,0 0,7 -7,0 z M 126,0 l 7,0 0,7 -7,0 z M 133,0 l 7,0 0,7 -7,0 z M 140,0 l 7,0 0,7 -7,0 z M 0,7 l 7,0 0,7 -7,0 z M 42,7 l 7,0 0,7 -7,0 z M 56,7 l 7,0 0,7 -7,0 z M 63,7 l 7,0 0,7 -7,0 z M 70,7 l 7,0 0,7 -7,0 z M 84,7 l 7,0 0,7 -7,0 z M 98,7 l 7,0 0,7 -7,0 z M 140,7 l 7,0 0,7 -7,0 z M 0,14 l 7,0 0,7 -7,0 z M 14,14 l 7,0 0,7 -7,0 z M 21,14 l 7,0 0,7 -7,0 z M 28,14 l 7,0 0,7 -7,0 z M 42,14 l 7,0 0,7 -7,0 z M 70,14 l 7,0 0,7 -7,0 z M 77,14 l 7,0 0,7 -7,0 z M 84,14 l 7,0 0,7 -7,0 z M 98,14 l 7,0 0,7 -7,0 z M 112,14 l 7,0 0,7 -7,0 z M 119,14 l 7,0 0,7 -7,0 z M 126,14 l 7,0 0,7 -7,0 z M 140,14 l 7,0 0,7 -7,0 z M 0,21 l 7,0 0,7 -7,0 z M 14,21 l 7,0 0,7 -7,0 z M 21,21 l 7,0 0,7 -7,0 z M 28,21 l 7,0 0,7 -7,0 z M 42,21 l 7,0 0,7 -7,0 z M 56,21 l 7,0 0,7 -7,0 z M 63,21 l 7,0 0,7 -7,0 z M 84,21 l 7,0 0,7 -7,0 z M 98,21 l 7,0 0,7 -7,0 z M 112,21 l 7,0 0,7 -7,0 z M 119,21 l 7,0 0,7 -7,0 z M 126,21 l 7,0 0,7 -7,0 z M 140,21 l 7,0 0,7 -7,0 z M 0,28 l 7,0 0,7 -7,0 z M 14,28 l 7,0 0,7 -7,0 z M 21,28 l 7,0 0,7 -7,0 z M 28,28 l 7,0 0,7 -7,0 z M 42,28 l 7,0 0,7 -7,0 z M 63,28 l 7,0 0,7 -7,0 z M 84,28 l 7,0 0,7 -7,0 z M 98,28 l 7,0 0,7 -7,0 z M 112,28 l 7,0 0,7 -7,0 z M 119,28 l 7,0 0,7 -7,0 z M 126,28 l 7,0 0,7 -7,0 z M 140,28 l 7,0 0,7 -7,0 z M 0,35 l 7,0 0,7 -7,0 z M 42,35 l 7,0 0,7 -7,0 z M 56,35 l 7,0 0,7 -7,0 z M 77,35 l 7,0 0,7 -7,0 z M 98,35 l 7,0 0,7 -7,0 z M 140,35 l 7,0 0,7 -7,0 z M 0,42 l 7,0 0,7 -7,0 z M 7,42 l 7,0 0,7 -7,0 z M 14,42 l 7,0 0,7 -7,0 z M 21,42 l 7,0 0,7 -7,0 z M 28,42 l 7,0 0,7 -7,0 z M 35,42 l 7,0 0,7 -7,0 z M 42,42 l 7,0 0,7 -7,0 z M 56,42 l 7,0 0,7 -7,0 z M 70,42 l 7,0 0,7 -7,0 z M 84,42 l 7,0 0,7 -7,0 z M 98,42 l 7,0 0,7 -7,0 z M 105,42 l 7,0 0,7 -7,0 z M 112,42 l 7,0 0,7 -7,0 z M 119,42 l 7,0 0,7 -7,0 z M 126,42 l 7,0 0,7 -7,0 z M 133,42 l 7,0 0,7 -7,0 z M 140,42 l 7,0 0,7 -7,0 z M 63,49 l 7,0 0,7 -7,0 z M 0,56 l 7,0 0,7 -7,0 z M 7,56 l 7,0 0,7 -7,0 z M 14,56 l 7,0 0,7 -7,0 z M 21,56 l 7,0 0,7 -7,0 z M 28,56 l 7,0 0,7 -7,0 z M 42,56 l 7,0 0,7 -7,0 z M 49,56 l 7,0 0,7 -7,0 z M 56,56 l 7,0 0,7 -7,0 z M 77,56 l 7,0 0,7 -7,0 z M 91,56 l 7,0 0,7 -7,0 z M 105,56 l 7,0 0,7 -7,0 z M 119,56 l 7,0 0,7 -7,0 z M 133,56 l 7,0 0,7 -7,0 z M 0,63 l 7,0 0,7 -7,0 z M 7,63 l 7,0 0,7 -7,0 z M 14,63 l 7,0 0,7 -7,0 z M 21,63 l 7,0 0,7 -7,0 z M 49,63 l 7,0 0,7 -7,0 z M 56,63 l 7,0 0,7 -7,0 z M 77,63 l 7,0 0,7 -7,0 z M 84,63 l 7,0 0,7 -7,0 z M 91,63 l 7,0 0,7 -7,0 z M 98,63 l 7,0 0,7 -7,0 z M 105,63 l 7,0 0,7 -7,0 z M 133,63 l 7,0 0,7 -7,0 z M 140,63 l 7,0 0,7 -7,0 z M 0,70 l 7,0 0,7 -7,0 z M 7,70 l 7,0 0,7 -7,0 z M 21,70 l 7,0 0,7 -7,0 z M 28,70 l 7,0 0,7 -7,0 z M 35,70 l 7,0 0,7 -7,0 z M 42,70 l 7,0 0,7 -7,0 z M 63,70 l 7,0 0,7 -7,0 z M 70,70 l 7,0 0,7 -7,0 z M 84,70 l 7,0 0,7 -7,0 z M 98,70 l 7,0 0,7 -7,0 z M 105,70 l 7,0 0,7 -7,0 z M 126,70 l 7,0 0,7 -7,0 z M 133,70 l 7,0 0,7 -7,0 z M 0,77 l 7,0 0,7 -7,0 z M 14,77 l 7,0 0,7 -7,0 z M 21,77 l 7,0 0,7 -7,0 z M 35,77 l 7,0 0,7 -7,0 z M 70,77 l 7,0 0,7 -7,0 z M 77,77 l 7,0 0,7 -7,0 z M 84,77 l 7,0 0,7 -7,0 z M 91,77 l 7,0 0,7 -7,0 z M 98,77 l 7,0 0,7 -7,0 z M 119,77 l 7,0 0,7 -7,0 z M 126,77 l 7,0 0,7 -7,0 z M 133,77 l 7,0 0,7 -7,0 z M 7,84 l 7,0 0,7 -7,0 z M 21,84 l 7,0 0,7 -7,0 z M 42,84 l 7,0 0,7 -7,0 z M 49,84 l 7,0 0,7 -7,0 z M 56,84 l 7,0 0,7 -7,0 z M 84,84 l 7,0 0,7 -7,0 z M 133,84 l 7,0 0,7 -7,0 z M 56,91 l 7,0 0,7 -7,0 z M 84,91 l 7,0 0,7 -7,0 z M 105,91 l 7,0 0,7 -7,0 z M 112,91 l 7,0 0,7 -7,0 z M 126,91 l 7,0 0,7 -7,0 z M 0,98 l 7,0 0,7 -7,0 z M 7,98 l 7,0 0,7 -7,0 z M 14,98 l 7,0 0,7 -7,0 z M 21,98 l 7,0 0,7 -7,0 z M 28,98 l 7,0 0,7 -7,0 z M 35,98 l 7,0 0,7 -7,0 z M 42,98 l 7,0 0,7 -7,0 z M 56,98 l 7,0 0,7 -7,0 z M 63,98 l 7,0 0,7 -7,0 z M 77,98 l 7,0 0,7 -7,0 z M 91,98 l 7,0 0,7 -7,0 z M 119,98 l 7,0 0,7 -7,0 z M 126,98 l 7,0 0,7 -7,0 z M 133,98 l 7,0 0,7 -7,0 z M 0,105 l 7,0 0,7 -7,0 z M 42,105 l 7,0 0,7 -7,0 z M 70,105 l 7,0 0,7 -7,0 z M 105,105 l 7,0 0,7 -7,0 z M 119,105 l 7,0 0,7 -7,0 z M 126,105 l 7,0 0,7 -7,0 z M 133,105 l 7,0 0,7 -7,0 z M 140,105 l 7,0 0,7 -7,0 z M 0,112 l 7,0 0,7 -7,0 z M 14,112 l 7,0 0,7 -7,0 z M 21,112 l 7,0 0,7 -7,0 z M 28,112 l 7,0 0,7 -7,0 z M 42,112 l 7,0 0,7 -7,0 z M 56,112 l 7,0 0,7 -7,0 z M 63,112 l 7,0 0,7 -7,0 z M 70,112 l 7,0 0,7 -7,0 z M 77,112 l 7,0 0,7 -7,0 z M 91,112 l 7,0 0,7 -7,0 z M 112,112 l 7,0 0,7 -7,0 z M 133,112 l 7,0 0,7 -7,0 z M 0,119 l 7,0 0,7 -7,0 z M 14,119 l 7,0 0,7 -7,0 z M 21,119 l 7,0 0,7 -7,0 z M 28,119 l 7,0 0,7 -7,0 z M 42,119 l 7,0 0,7 -7,0 z M 56,119 l 7,0 0,7 -7,0 z M 63,119 l 7,0 0,7 -7,0 z M 77,119 l 7,0 0,7 -7,0 z M 84,119 l 7,0 0,7 -7,0 z M 91,119 l 7,0 0,7 -7,0 z M 98,119 l 7,0 0,7 -7,0 z M 105,119 l 7,0 0,7 -7,0 z M 112,119 l 7,0 0,7 -7,0 z M 119,119 l 7,0 0,7 -7,0 z M 0,126 l 7,0 0,7 -7,0 z M 14,126 l 7,0 0,7 -7,0 z M 21,126 l 7,0 0,7 -7,0 z M 28,126 l 7,0 0,7 -7,0 z M 42,126 l 7,0 0,7 -7,0 z M 56,126 l 7,0 0,7 -7,0 z M 63,126 l 7,0 0,7 -7,0 z M 70,126 l 7,0 0,7 -7,0 z M 84,126 l 7,0 0,7 -7,0 z M 98,126 l 7,0 0,7 -7,0 z M 119,126 l 7,0 0,7 -7,0 z M 126,126 l 7,0 0,7 -7,0 z M 0,133 l 7,0 0,7 -7,0 z M 42,133 l 7,0 0,7 -7,0 z M 56,133 l 7,0 0,7 -7,0 z M 63,133 l 7,0 0,7 -7,0 z M 77,133 l 7,0 0,7 -7,0 z M 84,133 l 7,0 0,7 -7,0 z M 91,133 l 7,0 0,7 -7,0 z M 98,133 l 7,0 0,7 -7,0 z M 105,133 l 7,0 0,7 -7,0 z M 119,133 l 7,0 0,7 -7,0 z M 126,133 l 7,0 0,7 -7,0 z M 0,140 l 7,0 0,7 -7,0 z M 7,140 l 7,0 0,7 -7,0 z M 14,140 l 7,0 0,7 -7,0 z M 21,140 l 7,0 0,7 -7,0 z M 28,140 l 7,0 0,7 -7,0 z M 35,140 l 7,0 0,7 -7,0 z M 42,140 l 7,0 0,7 -7,0 z M 56,140 l 7,0 0,7 -7,0 z M 70,140 l 7,0 0,7 -7,0 z M 84,140 l 7,0 0,7 -7,0 z M 105,140 l 7,0 0,7 -7,0 z M 119,140 l 7,0 0,7 -7,0 z M 133,140 l 7,0 0,7 -7,0 z " />
	</g>
</svg>
````

I've no intuition on SVG rendering speed, but it might be worth checking if a single path like that is more efficient (at least the DOM is lighter, I guess).

**Comment by dbuenzli** [comment]
The SVG stuff was quickly hacked, feel free to PR something else that works along the line. As long as it works reasonably on V40 and that it respects SVG 1.1 I'm fine with merging another structure.

**Comment by alainfrisch** [comment]
I cannot make V40 work with the current version, even with a large zoom factor (neither from my smartphone, nor my taking a screenshot and sending it to an online reader).  Does it work on your side?

**Comment by dbuenzli** [comment]
Not sure exactly about your details but at least if I do: 

> qrtrip -f svg -v 40 https://erratique.ch  > bla.svg

and open the SVG file in chrome, the built-in camera app of iOS 14.3 scans that correctly.

**Comment by dbuenzli** [comment]
Closed by https://github.com/dbuenzli/qrc/commit/2c0e2b7e2534adc81ca5b0c3a3074f4836552c4f
