### ISSUE TITLE
Moving to_svg out of Qrc.Matrix?

### ISSUE THREAD

**Issue by alainfrisch** [dbuenzli/qrc#4]
(This is more for discussion rather than an actual issue.  Let me know if it is not the proper place to discuss.)

It doesn't feel natural to me to have the `to_svg` function in Qrc.Matrix, which conceptually is just an implementation of a data structure.  Other "backends" are in their own module Qrc_fmt.  Why no move to_svg there as well, or to a different unit, or just a different sub-module in Qrc?  And perhaps make it use a similar interface than other backends (i.e. taking a formatter as argument); or are you concerned by performance of to_svg itself (when running in the browser, I guess)?

**Comment by dbuenzli** [comment]
In fact if it were only me `Qrc_fmt` wouldn't exist and its printer would be in `Qrc.Matrix`. So if I find anything to be out of place it's  `Qrc_fmt.*`'s functions, not `Qrc.Matrix.to_svg` which I find quite natural.

The reason why formatters are in a separate module is that `js_of_ocaml` is unable to dead-code `Format` away which adds  [quite some weight](https://erratique.ch/software/brr/doc/web_page_howto.html#fmt) to web pages, *even if you don't use it*. 

This is also the reason for `Qrc.Matrix.to_svg`'s `formatter`less implementation and signature. It allows you to easily use it in the browser and inject the result in webpages without having to pay too much size-wise.

**Comment by alainfrisch** [comment]
Thanks, it makes sense now!
